### ISSUE TITLE
팀 이름 다시 정하기

### ISSUE THREAD

**Issue by jaesoekjjang** [monitmonit/dev#3]

**Comment by uuuuujin** [comment]
좋은 의견 있으신지요

**Comment by jaesoekjjang** [comment]
> 좋은 의견 있으신지요

amdin.js 윤상님한테 거부 당해서 다시 생각 중입니다.

**Comment by yanggak12** [comment]
팀명 : 드가자(DGAZA)
의미 : 급변하는 프론트엔드의 트렌드에 발맞춰 빠르게 나아가자는 뜻과 깊은 기술적인 지식으로 파고들자는 취지의 팀명입니다.
지적 및 피드백 환영합니다.

**Comment by jaesoekjjang** [comment]
> 팀명 : 드가자(DGAZA) 의미 : 급변하는 프론트엔드의 트렌드에 발맞춰 빠르게 나아가자는 뜻과 깊은 기술적인 지식으로 파고들자는 취지의 팀명입니다. 지적 및 피드백 환영합니다.

팀명은 드가자, 의미는 나아가자이군요.. 심오합니다

**Comment by yanggak12** [comment]
> > 팀명 : 드가자(DGAZA) 의미 : 급변하는 프론트엔드의 트렌드에 발맞춰 빠르게 나아가자는 뜻과 깊은 기술적인 지식으로 파고들자는 취지의 팀명입니다. 지적 및 피드백 환영합니다.
> 
> 팀명은 드가자, 의미는 나아가자이군요.. 심오합니다

자 드가자~

**Comment by jaesoekjjang** [comment]
Monit이란 팀명은 어떤지요 ㅎㅎ Monitoring의 앞자입니다. 마음에 들면 up 아니라면 down 눌러주세요~
